### ISSUE TITLE
Add PhpStorm codeStyle settings to repository

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/TYPO3-Distribution#113]
https://stackoverflow.com/questions/9087439/how-to-share-code-style-settings-between-developers-in-intellij
https://www.jetbrains.com/help/idea/code-style.html (Copy to Project...)
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839
https://www.jetbrains.com/help/phpstorm/configuring-code-style.html

**Comment by jousch** [comment]
https://github.com/Strider-CD/strider/blob/gh-pages/.idea/codeStyleSettings.xml

**Comment by josefglatz** [comment]
Finalized for now
