### ISSUE TITLE
Remove be_groups.hide_in_lists in default database records file

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/TYPO3-Distribution#151]
https://review.typo3.org/#/c/53179/

**Comment by georgringer** [comment]
I would remove if also for 8x to be consistent with the future

**Comment by georgringer** [comment]
@jousch this should already be done in 8, nobody needs that ;)

**Comment by jousch** [comment]
The problem is, that I can't remove it from the yaml default database record file, because otherwsie ext:yaml_configuration will have troubles executing db queries.

Is it already removed in 9-dev?

**Comment by josefglatz** [comment]
It's removed in 9-dev. Therefore, I remove it for master branch only
