### ISSUE TITLE
ViewHelper: "FindInArrayViewHelper"

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/TYPO3-Distribution#239]
then/else if any `foo.N.data.field` === specific value

## given array $array

- 0
  - data
    - field = foo
- 1
  - data
    - field = muh
- 2
  - data
    - field = cool

## some feature like

`<theme:findInArray haystack="{array}" needlePath="data.field" needleValue="muh" />`

## return
* *if value was found:* return amount of occurrences `(int) n`
* *if value was NOT found:* return `0`

**Comment by georgringer** [comment]
closing this, sounds very project specific and maybe better solveable in the model instead of that.
