### ISSUE TITLE
EXT:realurl: enhance autoConf

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/TYPO3-Distribution#269]
re-structure like https://bitbucket.org/reelworx/rx-typo3-base-distribution/src/22166b1da538d2065076833694b6765b5b4a54f5/packages/sitesetup/Classes/Hooks/RealUrl.php?at=master&fileviewer=file-view-default to get a better overview

**Comment by georgringer** [comment]
9 is the way to go, no realurl anymore
