### ISSUE TITLE
CommandController: Set .vm/.docker Domains active and sort to beginning after sync

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/TYPO3-Distribution#291]

**Comment by vkemeter** [comment]
i just added this one in a project for after sync. i am just too dump and lazy to add this to your project. sorry ;) this is a post sync command controller which can be extended on your demands. i added a method for enabling the vm/docker sys domain records based on the docker-compose.yml.

it worked like a charme for me.

but as we dont need extbase here we should refactor it to symfony console command and querybuilder like georg did:

https://github.com/georgringer/gdpr/blob/master/Classes/Command/AnonymizeIpCommand.php

we can do that in our hackathon/podcast session ;)

```
<?php
namespace Supseven\O5ThmGsederl\Command;

use \TYPO3\CMS\Extbase\Mvc\Controller\CommandController;

class PostSyncCommandController extends CommandController
{

    public function enableDevSysDomainsCommand()
    {
        if (isset($_SERVER['VIRTUAL_HOST'])) {
            $enableTld = array_values(array_slice(explode('.', array_values(array_slice(explode(' ', $_SERVER['VIRTUAL_HOST']), -1))[0]), -1))[0];

            $this->getDb()->exec_UPDATEquery(
                'sys_domain',
                'hidden = 1 AND domainName LIKE "%.'. $this->getDb()->escapeStrForLike($enableTld, '') .'"',
                [
                    'hidden' => 0,
                    'sorting' => 0,
                ]
            );

            $this->outputLine($this->getDb()->sql_affected_rows() .' Domains for *.'. $enableTld .' where enabled and sorted on top!');

        }
    }

    /**
     * @return mixed|\TYPO3\CMS\Core\Database\DatabaseConnection
     */
    private function getDb() {
        return $GLOBALS['TYPO3_DB'];
    }
}
```

**Comment by josefglatz** [comment]
@vkemeter could you please review my change - thx in advance // CC @georgringer is also invited to review the command controller :-)
