### ISSUE TITLE
Use typo3/minimal instead of typo3/cms

### ISSUE THREAD

**Issue by georgringer** [josefglatz/TYPO3-Distribution#314]
By using `typo3/minimal` it is possible to just have those sysexts which are mentioned in the composer.json file and not all of them

**Comment by josefglatz** [comment]
@georgringer should i not continue require `typo3/cms-core`? I've added the latest changes to my composer.json. Would be nice if you could take a look https://github.com/josefglatz/TYPO3-Distribution/blob/master/app/composer.json and give feedback.
