### ISSUE TITLE
Improve ext_conf_template handling

### ISSUE THREAD

**Issue by georgringer** [josefglatz/TYPO3-Distribution#375]
Currently the distribution has a lot of those serialize() stuff in the additional configuration files.

- [ ]  Use the new syntax (without serialized) for core stuff 
- [ ] Check which ones can be removed (either ext is not in require section anymore or not needed, e.g rsaauth)

**Comment by josefglatz** [comment]
@georgringer fixed already 13 days ago in ac9f7bfc4b51882df56ae1af5c3c7a9e86c9f4a6

plz re-open if I don't get your points
