### ISSUE TITLE
Move sys_template restriction to custom extension

### ISSUE THREAD

**Issue by georgringer** [josefglatz/TYPO3-Distribution#387]
Hiding sys_template & disabling the creation of it is a perfect example for a custom extension. reasons are:

- people who still use TS templates can still use the ext
- theme is less bloated with stuff
- people who got different site packages can also use the new ext

**Comment by georgringer** [comment]
@josefglatz testing + move to packagist

**Comment by josefglatz** [comment]
Done in v9 branch
