### ISSUE TITLE
FSC final rewrite changes

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/TYPO3-Distribution#85]

**Comment by jousch** [comment]
https://bitbucket.org/reelworx/rx-typo3-sitesetup/commits/880ebf28be2feebf9c9f95370251ff088e1d1869

**Comment by georgringer** [comment]
@jousch should we close that issue?

**Comment by jousch** [comment]
Hmm.. hard to say. My intention was to not add default frontend templates for our common content elements. I'm think about some default CE's. Maybe we should add this to a different "content"-extension?
