### ISSUE TITLE
Speed up first setup

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/TYPO3-Distribution#88]
1. Download repo and combine together with webdevops/TYPO3-docker-boilerplate
2. Set up your docker-boilerplate
3. Adjust `app/composer.json` to your needs
4. `composer install`
5. Initial TYPO3 installation with one CLI task
6. Initial default database records with one CLI task
7. Initial setup of active extensions
8. Commit your changes at least now

**Comment by jousch** [comment]
## Needed facts

- MySQL Server Version
- PHP Version
- Webserver Typ
- PMA aktiv?
- Mailhog aktiv?
- BE Name
- BE Passwort
-
